### ISSUE TITLE
Registrarse

### ISSUE THREAD

**Issue by Exequiel2294** [sebarigonatto/sinu#10]
En registrarse al momento de seleccionar la delegación mostrar sus datos (Dirección y Numero de teléfono)
![image](https://user-images.githubusercontent.com/62607044/84147744-4c19c500-aa34-11ea-932a-fbae903470d6.png)

**Comment by emanuelvelasquez** [comment]
Ahora al seleccionar un a delegación/oficina en esta pantalla se mostraran los datos del mismo.
