### ISSUE TITLE
Correo electronico existente al crear Delegacion Corrientes

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#102]
Los correos los invente yo: delecor@gmail.com y correr@gmail.com
![image](https://user-images.githubusercontent.com/66480359/96748262-eac51380-138e-11eb-8733-ee5ccf8df8b3.png)

**Comment by emanuelvelasquez** [comment]
Probando la creación de un usuario "Delegacion", me salto este error, pero por que el el armado del correo estaba mal y me redirigió a la pantalla de "Error" después de haber creado al usuario (faltaba un dato en el modelo). Nose si por la misma razon te sucedio a vos. Corrigiendo este error al enviar el correo,  la creación de un nuevo usuario se realizo normalmente.

**Comment by germanvh** [comment]
Despues lo pruebo con la nueva version.

**Comment by germanvh** [comment]
Lo probe en la version web, intentando crear un usuario delegacion desde Perfil Administrador y me salio esto, no se si es el mismo error:
![image](https://user-images.githubusercontent.com/66480359/98489889-72b37600-21f5-11eb-98e2-b226284d954f.png)
