### ISSUE TITLE
No salen datos en los combos luego de la Entrevista y Postulacion, al llenar los datos personales

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#103]
![image](https://user-images.githubusercontent.com/66480359/97723529-83474c00-1a91-11eb-8011-a6c75f7fa134.png)

**Comment by emanuelvelasquez** [comment]
Las últimas modificaciones que tienen que ver con convocatorias requieren más controles sobre el armado de las mismas. Corregido las mismas ya se muestran las modalidades correctamente
