### ISSUE TITLE
Error al solicitar validar los datos en Postulante

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#105]
![image](https://user-images.githubusercontent.com/66480359/98490447-2832f900-21f7-11eb-8f0a-11ba0aea5149.png)

**Comment by emanuelvelasquez** [comment]
podrás verificar nuevamente este error, porque realizandolo con mi cuenta realiza la petición de validación normalmente. Si sigue podes probar borrar al usuario e inscribirte nuevamente, algo similar sucedía con otra cuenta resulta que los cambio en la base datos recientes causan errores en usuarios viejos.

**Comment by germanvh** [comment]
Si. Sigue. Voy a probar con otro usuario.

**Comment by germanvh** [comment]
Sigue sucediendo con otro usuario que hice luego.
