### ISSUE TITLE
La fecha sale en otro "formato" que en el issue anterior que yo mande.

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#11]
Y la edad es -1 y antes era -2.
Esto sucedio despues de pasar de etapa a "Documentacion". Quizas esta bien. Lo dejo aca para acordarme.
![image](https://user-images.githubusercontent.com/66480359/84148363-453f8200-aa35-11ea-8e77-949e57266a6c.png)

![image](https://user-images.githubusercontent.com/66480359/84148561-92bbef00-aa35-11ea-9b4e-1d2bc7f64af0.png)

**Comment by emanuelvelasquez** [comment]
Corregido el Cambio de Formato de la Fecha de Cumpleaños, al momento de guardar los datos.
