### ISSUE TITLE
Agregar adjunto Mail etapa Confirmar Entrevista

### ISSUE THREAD

**Issue by sebarigonatto** [sebarigonatto/sinu#130]
[ASPECTOS A INFORMAR.docx](https://github.com/sebarigonatto/sinu/files/6392657/ASPECTOS.A.INFORMAR.docx)

**Comment by sebarigonatto** [comment]
Te recordamos que concurras a la misma con la documentacion adjunta debidamente confeccionada. En caso de no poder concurrir comunicarse con la delegacion para reprogramar la entrevista

**Comment by emanuelvelasquez** [comment]
Se sumo al email de "Entrevista Asignada" el adjunto  mencionado y el texto.
