### ISSUE TITLE
Calculo EDAD 0 permite registrarse y SMV

### ISSUE THREAD

**Issue by sebarigonatto** [sebarigonatto/sinu#142]
![image](https://user-images.githubusercontent.com/8737392/121394691-f9fdcf00-c927-11eb-9ecf-654f9b71011c.png)

**Comment by sebarigonatto** [comment]
Debera controlarse La edad ante la solicitud de entrevista, debera estar comprendida dentro restricciones de edad y presentar el error al usuario en la Etapa Carga Datos Basicos, 

Alternativa Permitir la edicion del campo Fecha de Nacimiento en la Etapa Documentacion.

**Comment by emanuelvelasquez** [comment]
Se agregaron en la solapa de "Documentación", los campos necesarios para la modificación de la Edad de los Postulantes.
