### ISSUE TITLE
Eliminacion Postulante Administrador

### ISSUE THREAD

**Issue by sebarigonatto** [sebarigonatto/sinu#144]
El administrador debera contar con la accion eliminacion del Postulante a partir de un listado de  postulantes que se encuentren con convocatoria activas.
Evualuar: el administrador buscara por DNI,Email, apellido nombre, numero de preinscripcion, Modalidad, convocatoria: presentando el listado dispondra la accion eliminar. Actualmente el Administrador no cuenta con la posibilidad de ver la informacion de los postulantes (ver Detalle).
Evaluar: dejar registro de la accion y causa de eliminacion apartir de un comentario libre por parte del administrador.

**Comment by emanuelvelasquez** [comment]
Funcionalidad hecha y visible en el menú el perfil ADMINISTRADOR, búsqueda de postulantes según los campos indicados, también se deja registro de la eliminación de un postulante en  la tabla "AccesosEliminados".
