### ISSUE TITLE
Se puede tocar metadatos.cs?

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#21]
No se si se puede tocar este archivo, asi corrijo algunos labels que estan igual que el campo pero deberian tener un nombre mas adecuado.

**Comment by Nekourashima** [comment]
Si German, fijate si esas etiquetas no estan subidas en las Issus asi vamos cerrando cada una segun se hagan.

**Comment by germanvh** [comment]
Ok.
