### ISSUE TITLE
Error al completar datos de familiar, en la segunda solapa

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#23]
Le habia puesto nacionalidad Armenia, pero el error creo que fue otro. Pero cuando puse esa nacionalidad salio el error.
![image](https://user-images.githubusercontent.com/66480359/84177287-0a4f4580-aa59-11ea-9acf-b48a63fdf91c.png)

![image](https://user-images.githubusercontent.com/66480359/84177387-2eab2200-aa59-11ea-8b61-22ce6491ee27.png)

**Comment by emanuelvelasquez** [comment]
Subidos cambios para solucionar problemas del combobox
