### ISSUE TITLE
Cuando entro con usuario delegacion falta completar la pag Contacto

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#27]
Contact
Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, eveniet earum. Sed accusantium eligendi molestiae quo hic velit nobis et, tempora placeat ratione rem blanditiis voluptates vel ipsam? Facilis, earum!

**Comment by Exequiel2294** [comment]
cambios realizado, en la pagina contacto muestra los contactos de las delegaciones navales de las distintas provincias
