### ISSUE TITLE
Al modificar usuario en modo administrador

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#28]
Le agrego un grado y lo grabo

![image](https://user-images.githubusercontent.com/66480359/84383839-6cc45500-abc3-11ea-8c7f-bee5ec0624cb.png)

Pero no graba nada, cuando vuelvo:

![image](https://user-images.githubusercontent.com/66480359/84383918-91203180-abc3-11ea-81bf-0d224efe28f2.png)

**Comment by Nekourashima** [comment]
Ahora muestra el grado que tiene el usuario y lo selecciona directamente del combo.
