### ISSUE TITLE
Pantalla Oficinas Y Delegaciones (Administrador)

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#30]
Me sale por fuera de la pagina, como si tuviera un zoom.
![image](https://user-images.githubusercontent.com/66480359/84390772-6daeb400-abce-11ea-890d-cc37ce325e55.png)

**Comment by emanuelvelasquez** [comment]
Modificado el ancho de la tabla.
![image](https://user-images.githubusercontent.com/48690098/84398129-f0873d00-abd5-11ea-9e4f-99d39fd428b6.png)
