### ISSUE TITLE
No me funciona bien pantalla de Estudios

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#31]
Antes funcionaba me parece.
No andan los combos.
![image](https://user-images.githubusercontent.com/66480359/84392883-49a0a200-abd1-11ea-83bc-fac071680d60.png)

**Comment by emanuelvelasquez** [comment]
Subida la modificación para corregir la pantalla al agregar un Estudio.
![image](https://user-images.githubusercontent.com/48690098/84394647-9a18ff00-abd3-11ea-9766-241131aebe5a.png)
