### ISSUE TITLE
Espadol: Caracter erroneo.

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#35]
![image](https://user-images.githubusercontent.com/66480359/84780205-b0500200-afbb-11ea-89b2-5da02d62f837.png)

No se si es problema mio.

**Comment by sebarigonatto** [comment]
vamos a verificar la base de datos para ver como se encuentra el valor almacenado

**Comment by LCOttino** [comment]
Esto no depende de la base sino del juego de caracteres usado en el sistema de ejecucion.
También puede ser un problema en como está definida tu base qué juegos de caracteres usa.. pero si provino de un backup no debiera ser un problema.
ALTAMENTE probable que es el juego de caracteres usado en la pantalla del usuario tester

**Comment by LCOttino** [comment]
Debo verificarlo en mi pantalla pero me está produciendo otro error y no llego.. Otra posibilidad es como se manipula desde el código.....pero no creo que sea esto.. lo hubiera detectado antes Emanuel
