### ISSUE TITLE
No graba campo Grado

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#59]
El campo grado ya lo habia grabado, en administracion de usuarios en modo administrador. Y cuando vuelvo esta en blanco.
![image](https://user-images.githubusercontent.com/66480359/86064549-c9d55d00-ba43-11ea-8010-83b3b2c85794.png)

**Comment by Nekourashima** [comment]
creo que esto estaba en un mensaje anterior, que quedo pendiente, porque graba, pero no lo muestra. Si es otro problema distinto avisame. Creo que era este: https://github.com/sebarigonatto/sinu/issues/28

**Comment by germanvh** [comment]
Si, creo que es el mismo. Lo cierro?
