### ISSUE TITLE
Pagina Acerca De y Contacto

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#6]
Completar Pagina Acerca De.

Pagina Contacto tiene un email particular de prueba. Completarlo con datos reales.

**Comment by Nekourashima** [comment]
Cumplido con los datos de la pagina actual de incorporación

**Comment by germanvh** [comment]
No lo cierro, porque faltaria Acerca De, no?

**Comment by Nekourashima** [comment]
Listo German, quite Acerca de. Cierro.
