### ISSUE TITLE
Error al eliminar Sexo

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#60]
Sale cuando quiero eliminar el sexo Mujer, es porque hay datos con ese sexo que no lo puede eliminar, pero no deberia salir este error:
![image](https://user-images.githubusercontent.com/66480359/86199598-e8655200-bb30-11ea-9b5e-8a4539bbf719.png)

**Comment by LCOttino** [comment]
En la pantalla del Perfil _Administrador_ correspondiente a la tabla paramétrica _SEXO_ falta realizar el try catch correspondiente alrededor del bloque de código que contiene a la _línea 112_ en el archivo **SexoesCotroller.cs**. 

El  bloque catch capturará el error y podremos verificar el error. 
Si el error capturado corresponde al caso en que exista relaciones debe aclararse al usuario que dicho registro se encuentra relacionado con otros y por ello no puede eliminar el registro seleccionado.
Nunca ocurrirá este error si el registro a eliminar corresponde a un parámetro no usado aún en ninguna referencia en ningún registro de persona.

En este tipo de tablas paramétricas **solo se puede modificar la DESCRIPCIÓN**, es decir Varón puede cambiar a V o H  u Hombre o Masculino, etc. Los IDS no se modifican.
