### ISSUE TITLE
Error cuando apunto la base a otra que no es la mia

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#62]
Antes salia bien el error pero ahora es distinto, se queda en la funcion de armar el error.
![image](https://user-images.githubusercontent.com/66480359/86417842-a65d1d00-bca4-11ea-9353-685718ae5622.png)

**Comment by germanvh** [comment]
Parece que en el web.config quedo un nombre de maquina de alguien que trabaja desde su casa.

**Comment by Nekourashima** [comment]
acabo de reemplazar el webconfig por el original que apunta a BD siecsi14d
