### ISSUE TITLE
Error apenas hago correr el sistema.

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#63]
Sera algo de la base de datos?
![image](https://user-images.githubusercontent.com/66480359/86734778-a5135380-c008-11ea-815e-d0b793aba363.png)

**Comment by Nekourashima** [comment]
ayer se subió la actualización del modelo, hoy se va a ver el tema para salvar el mismo.

**Comment by germanvh** [comment]
Lo pude solucionar, toqueteando aca y alla, pero tengo miedo de haber hecho c..das.
