### ISSUE TITLE
Error al validar postulante

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#67]
![image](https://user-images.githubusercontent.com/66480359/86878657-cd11be00-c0bf-11ea-8318-75caa01d9c11.png)
![image](https://user-images.githubusercontent.com/66480359/86878742-f9c5d580-c0bf-11ea-8cad-400325c6e873.png)

**Comment by Exequiel2294** [comment]
Se corrigieron y se realizaron cambios ya no debería haber estos tipos de errores (Teniendo los últimos cambios y la base de dato actualizada).
