### ISSUE TITLE
Link Postulante desaparece

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#7]
Link Postulante desaparece del menu en el encabezado cuando vuelvo a SINU, cliqueando sobre el logo del sistema.

![Captura](https://user-images.githubusercontent.com/66480359/84062421-a1eb6000-a995-11ea-8e8f-a914a8285905.PNG)
![Captura2](https://user-images.githubusercontent.com/66480359/84062425-a283f680-a995-11ea-84e6-ec3008968ab0.PNG)

**Comment by emanuelvelasquez** [comment]
Realizados los cambios para mostrar los enlaces, comentados anteriormente, en la vista "SINU/Home". Lo mismos dependen del Perfil del Usuario que se encuentre logueado.
