### ISSUE TITLE
Creo que hay un error aca

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#74]
En el codigo se busca idSecuencia = 12 pero cuando no existe ese idSecuencia al no encontrar nada, va a tirar error si le hago FirstOrDefault, yo tengo ese error.
![image](https://user-images.githubusercontent.com/66480359/88174306-76959b00-cbfa-11ea-9e89-684e5ce68d31.png)

**Comment by emanuelvelasquez** [comment]
Ver si persiste este error.

**Comment by germanvh** [comment]
No lo puedo probar porque ahora tiene otro error, no se cual.

**Comment by emanuelvelasquez** [comment]
Cierro este inssue, ya que no se presenta el error mensionado.
