### ISSUE TITLE
Error al crear usuario desde perfil administrador

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#75]
Me sale este error con cualquier mail que ponga
![image](https://user-images.githubusercontent.com/66480359/88177427-3c7ac800-cbff-11ea-806a-b5ac2d129573.png)

**Comment by emanuelvelasquez** [comment]
Podes especificar que datos usaste cuando salio este error, aquí  con la Base de Datos del servidor "siecsi14d" la creación un nuevo usuario administrativo se da con normalidad.

**Comment by germanvh** [comment]
Tal vez tenga mal mi base de datos. Me la paso Johanna pero no se si fue la ultima, o me falta hacer algo cuando le hago el restore.

**Comment by germanvh** [comment]
El error se da al crear un usuario "postulante". El usuario "administrador" yo tambien lo puedo crear.

**Comment by germanvh** [comment]
Ya se lo que pasa. El error no tiene nada que ver con el mail. Cualquier error que sale dice eso, porque en el codigo esta que diga eso. Pero lo que pasa es que al ingresar a seguridad no puede poner en null el idsecuenciaestado o algo asi. No acepta null, porque no esta el postulante en la tabla postulante, ni en inscripcion. Y como Administrador no necesita (creo) estar en esas tablas, no hay problema.
