### ISSUE TITLE
Error en antropometria, al grabar, estan todos los campos llenos, creo

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#78]
![image](https://user-images.githubusercontent.com/66480359/93133712-44a23180-f69d-11ea-886b-5d75b599459e.png)

**Comment by emanuelvelasquez** [comment]
Este error puede a ver sucedido si se ingreso un numero decimal. Probar nuevamente

**Comment by germanvh** [comment]
Hay un numero decimal. Creo que es el IMC. Pero se calcula solo. Se pone solo como decimal.

**Comment by emanuelvelasquez** [comment]
Si ese seria el unico en decimal que se acepta en este formulario.
