### ISSUE TITLE
Error al crear nuevo grupo en Convocatoria -> Nuevo Registro. Fijarse que dice "NuevA Grupo".

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#86]
![image](https://user-images.githubusercontent.com/66480359/93973625-1c1fd480-fd3a-11ea-96fc-0f507195e4e7.png)

![image](https://user-images.githubusercontent.com/66480359/93973758-5ab58f00-fd3a-11ea-9574-042e5ffde7f8.png)

![image](https://user-images.githubusercontent.com/66480359/93973829-7c167b00-fd3a-11ea-89d9-4c5ea779db99.png)

![image](https://user-images.githubusercontent.com/66480359/93973867-889ad380-fd3a-11ea-805c-dd1c1420800b.png)

**Comment by Nekourashima** [comment]
no entiendo el problema, o sea, son dos? convocatorias por un lado y grupocarreraoficio por otro?

**Comment by Nekourashima** [comment]
ayer subi unos cambios y creo que corrije el error en grupocarreraoficio, en convocatoria probe las alternativas y no me da error, especificame que campos cargaste y que no para ver el error mas claro

**Comment by germanvh** [comment]
Ahora lo veo

**Comment by germanvh** [comment]
Esto sucede todo desde Convocatoria. Al hacer Nuevo Registro, se pueden ir dando de alta cada cosa. Daba error cuando lo daba de alta. El error es el mismo tanto el de abajo como el de arriba, puse las dos pantallas por si una daba mas informacion que la otra. Lo que si es otro error es un orror ortografico que dice NuevA Grupo. Habria que cambiarlo por NuevO.

**Comment by germanvh** [comment]
Este error salia cuando le daba "nuevo grupo", perdon que no habia puesto ese dato.

**Comment by Nekourashima** [comment]
ahora que lo veo, si no lo entendi mal, ese error viene cuando guardas  y faltan campos, al volver del controlador a la vista, no cargaba un listado (lstresgrupo), eso lo corregi. Tambien resulto que esa pantalla la subi para no perder los cambios, lo de restricciones no estaba hecho, solo mostraba un combo.
