### ISSUE TITLE
El campo es obligatorio pero no deja cambiarlo. Convocatoria -> Nuevo Registro.

### ISSUE THREAD

**Issue by germanvh** [sebarigonatto/sinu#87]
![image](https://user-images.githubusercontent.com/66480359/93974004-cbf54200-fd3a-11ea-9252-fa5b6cf20b19.png)

**Comment by Nekourashima** [comment]
ahi subi un cambio para que cuando vuelva el error de no elegir el campo, este habilitado, ahora puede elegir el campo sin elegir modalidad (cuando elige modalidad se vuelve a cargar el combo carrera/oficio).
