### ISSUE TITLE
Pagina CONTACTO.

### ISSUE THREAD

**Issue by Exequiel2294** [sebarigonatto/sinu#9]
Ingresar los datos del departamento de incorporación de DGPN

**Comment by Nekourashima** [comment]
Modifiqué los datos en la bd para que los obtenga desde allí, si no cambian los mismo en las bd locales no verán los cambios reflejados, en lo que es código html le agregue un Espacio para que no este todo junto. Adjunto la imagen con los campos modificados (datos actualizados de la tabla dbo.Configuracion):
![image](https://user-images.githubusercontent.com/65411738/84491283-af953400-ac7a-11ea-91ee-67b0111079df.png)

**Comment by Nekourashima** [comment]
Finalizado.
