### ISSUE TITLE
Vista Gestion de Cuenta

### ISSUE THREAD

**Issue by sebarigonatto** [sebarigonatto/sinu#99]
- [x] quitar Inicios de sesión externos: 0 [ Administrar ]![image](https://user-images.githubusercontent.com/8737392/96257701-35125300-0f91-11eb-9111-6e65cc46e025.png)
- [x] quitar Autenticación de dos factores: No hay ningún proveedor de autenticación en dos fases configurado. Consulte este artículo para obtener detalles sobre cómo configurar esta aplicación ASP.NET para que sea compatible con la autenticación en dos fases. ![image](https://user-images.githubusercontent.com/8737392/96258204-05177f80-0f92-11eb-897f-572f3df375eb.png)

**Comment by emanuelvelasquez** [comment]
Se quitaron ambas opciones, únicamente se le presenta el cambio de contraseña.
